gcc -pthread -Wall -Wextra -g -o pthreads pthreads.c
gcc -pthread -Wall -Wextra -g -o pthreadspl pthreadspl.c
gcc -pthread -Wall -Wextra -g -o pthreadstas pthreadstas.c
gcc -pthread -Wall -Wextra -g -o pthreadstatas pthreadstatas.c
clear
